### ISSUE TITLE
Question about resolution

### ISSUE THREAD

**Issue by ashpool** [geraldoramos/pigeon#10]
I'm having trouble setting the resolution above the default 640x480. Is it even possible or am I missing something?

**Comment by geraldoramos** [comment]
You can change by editing `pigeon.conf` file (lines 104 and 107).

The problem is the motion detection part. The same video used for watching/recording is used by the software to detect motion. I couldn't find a great way to be able to generate 2 different feeds, a low-quality one for motion detection and a higher quality for visualization. There are some implementations out there, but I couldn't make it work properly for this project and honestly, I've been busy and didn't have time to work on this project lately. It would we awesome to find contributors, but I couldn't so far.

I tried to make the default video configuration as decent as possible, but it will never be as good as a recording/playing-only solution.
